sudo: false
language: c
compiler:
  - clang
  - gcc
os: linux
env:
  - CONFIG=bios
  - CONFIG=efi-amd64
  - CONFIG=efi-ia32
install: true
script:
  - scons CONFIG=$CONFIG loader
  - scons CONFIG=$CONFIG test
  - scons utilities
